# Generated by Django 2.1.7 on 2020-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('ureal_name', models.CharField(default='',max_length=100)),
                ('upwd', models.CharField(max_length=100)),
                ('uemail', models.CharField(max_length=100)),
                ('uphone', models.CharField(default='无', max_length=100)),
                ('uaddress', models.CharField(default='无', max_length=100)),
                ('upostcode', models.CharField(default='无', max_length=100)),
                ('utelephone', models.CharField(default='无', max_length=100)),
            ],
        ),
    ]
